# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QMainWindow

import py

yz = 0
yz2 = 0
tag = 0
strr = ""
operator = ['+', '-', '*', '/']
chr = ''
chr2 = ''
tag_op=0


def click_success():
    global tag
    global strr
    global yz
    global tag_op

    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "1"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        tag_op=1
        strr = ui.lineEdit.text()
        strr += "1"
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success2():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "2"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        tag_op=1
        strr = ui.lineEdit.text()
        strr += "2"
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success3():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "3"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "3"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success4():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "4"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "4"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success5():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "5"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "5"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success6():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "6"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "6"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success7():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "7"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "7"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success8():
    global tag
    global strr
    global yz
    global tag_op

    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "8"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "8"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success9():
    global tag
    global strr
    global yz
    global tag_op
    if tag == 0:
        strr = ""
        tag = 1
        tag_op=1
        strr += "9"
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "9"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def click_success13():
    global tag
    global strr
    global yz
    global tag_op

    if tag == 0:
        strr = ""
        tag = 1
        strr += "0"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )
    else:
        strr = ui.lineEdit.text()
        strr += "0"
        tag_op=1
        ui.lineEdit.setText( strr )
        yz = int( strr )


def op_jia():
    global chr
    global chr2
    global yz
    global yz2
    global tag
    global tag_op
    if chr == '':
        yz2 = yz
        chr = '+'
        tag = 0
        chr2 = chr
        tag_op = 0
    else:
        tag = 0
        chr2 = chr
        if tag_op==1:
            if chr2 == '+':
                yz2 += yz
            elif chr2 == '-':
                yz2 -= yz
            elif chr2 == '*':
                yz2 *= yz
            elif chr2 == '/':
                yz2 /= yz
            ui.lineEdit.setText( str( yz2 ) )
            chr = '+'
            tag_op=0
        else:
            chr='+'
            chr2=''
            tag_op=0




def op_jian():
    global chr
    global chr2
    global yz
    global yz2
    global tag
    global tag_op
    if chr == '':
        yz2 = yz
        chr = '-'
        tag = 0
        chr2 = chr
        tag_op = 0
    else:
        tag = 0
        chr2 = chr
        if tag_op == 1:
            if chr2 == '+':
                yz2 += yz
            elif chr2 == '-':
                yz2 -= yz
            elif chr2 == '*':
                yz2 *= yz
            elif chr2 == '/':
                yz2 /= yz
            ui.lineEdit.setText( str( yz2 ) )
            chr = '-'

            tag_op = 0
        else:
            chr = '-'
            chr2 = ''
            tag_op = 0


def op_cheng():
    global chr
    global chr2
    global yz
    global yz2
    global tag
    global tag_op
    if chr == '':
        yz2 = yz
        chr = '*'
        tag = 0
        chr2 = chr
        tag_op = 0
    else:
        tag = 0
        chr2 = chr
        if tag_op == 1:
            if chr2 == '+':
                yz2 += yz
            elif chr2 == '-':
                yz2 -= yz
            elif chr2 == '*':
                yz2 *= yz
            elif chr2 == '/':
                yz2 /= yz
            ui.lineEdit.setText( str( yz2 ) )
            chr = '*'

            tag_op = 0
        else:
            chr = '*'
            chr2 = ''
            tag_op = 0


def op_chu():
    global chr
    global chr2
    global yz
    global yz2
    global tag
    global tag_op
    if chr == '':
        yz2 = yz
        chr = '/'
        tag = 0
        chr2 = chr
        tag_op = 0
    else:
        tag = 0
        chr2 = chr
        if tag_op == 1:
            if chr2 == '+':
                yz2 += yz
            elif chr2 == '-':
                yz2 -= yz
            elif chr2 == '*':
                yz2 *= yz
            elif chr2 == '/':
                if yz!=0:
                    yz2 /= yz
                else:
                    yz2=0
            ui.lineEdit.setText( str( yz2 ) )
            chr = '/'

            tag_op = 0
        else:
            chr = '/'
            chr2 = ''
            tag_op = 0


def click_dengyu():
    global tag
    global strr
    global yz
    global yz2
    tag = 0
    yz = int(strr)
    if chr == '+':
        yz2 += yz
    elif chr == '-':
        yz2 -= yz
    elif chr == '*':
        yz2 *= yz
    elif chr == '/':
        if yz != 0:
            yz2 /= yz
        else:
            yz2 = 0
    ui.lineEdit.setText( str( yz2 ) )
    click_ql1()

def click_ql():
    global tag
    global strr
    global yz
    global yz2
    global chr
    global chr2
    tag = 0
    ui.lineEdit.setText( "0" )
    strr=""
    chr=''
    chr2=''
    yz=0
    yz2=0

def click_ql1():
    global tag
    global strr
    global yz
    global yz2
    global chr
    global chr2
    tag = 0
    strr="0"
    chr=''
    chr2=''
    yz=0
    yz2=0

if __name__ == '__main__':
    app = QApplication( sys.argv )
    MainWindow = QMainWindow()
    ui = py.Ui_MainWindow()
    ui.setupUi( MainWindow )
    MainWindow.setWindowTitle("计算器")
    MainWindow.show()



    ui.pushButton.clicked.connect( click_success )
    ui.pushButton_2.clicked.connect( click_success2 )
    ui.pushButton_3.clicked.connect( click_success3 )
    ui.pushButton_4.clicked.connect( click_success4 )
    ui.pushButton_5.clicked.connect( click_success5 )
    ui.pushButton_6.clicked.connect( click_success6 )
    ui.pushButton_7.clicked.connect( click_success7 )
    ui.pushButton_8.clicked.connect( click_success8 )
    ui.pushButton_9.clicked.connect( click_success9 )
    ui.pushButton_13.clicked.connect( click_success13 )

    ui.pushButton_10.clicked.connect( op_jia )
    ui.pushButton_11.clicked.connect( op_jian )
    ui.pushButton_12.clicked.connect( op_cheng )
    ui.pushButton_14.clicked.connect( op_chu )

    ui.pushButton_15.clicked.connect( click_dengyu )
    ui.pushButton_16.clicked.connect( click_ql )
    sys.exit( app.exec_() )
